* Sugestões
** Algumas regras devem ser observadas na redação da monografia:
*** É recomendável que o número total de páginas referente à parte de desenvolvimento não ultrapasse 60 (sessenta) páginas.
*** ser claro, preciso, direto, objetivo e conciso, utilizando frases curtas e evitando ordens inversas desnecessárias;
*** construir períodos com no máximo duas ou três linhas, bem como parágrafos com cinco linhas cheias, em média, e no máximo oito (ou seja, não construir parágrafos e períodos muito longos, pois isso cansa o(s) leitor(es) e pode fazer com que ele(s) percam a linha de raciocínio desenvolvida);
*** a simplicidade deve ser condição essencial do texto; a simplicidade do texto não implica necessariamente repetição de formas e frases desgastadas, uso exagerado de voz passiva (como \textit{será iniciado}, \textit{será realizado}), pobreza vocabular etc. Com palavras conhecidas de todos, é possível escrever de maneira original e criativa e produzir frases elegantes, variadas, fluentes e bem alinhavadas;
*** adotar como norma a ordem direta, por ser aquela que conduz mais facilmente o leitor à essência do texto, dispensando detalhes irrelevantes e indo diretamente ao que interessa, sem rodeios (verborragias);
*** não começar períodos ou parágrafos seguidos com a mesma palavra, nem usar repetidamente a mesma estrutura de frase;
*** desprezar as longas descrições e relatar o fato no menor número possível de palavras;
*** recorrer aos termos técnicos somente quando absolutamente indispensáveis e nesse caso colocar o seu significado entre parênteses (ou seja, não se deve admitir que todos os que lerão o trabalho já dispõem de algum conhecimento desenvolvido no mesmo);
*** dispensar palavras e formas empoladas ou rebuscadas, que tentem transmitir ao leitor mera idéia de erudição;
*** não perder de vista o universo vocabular do leitor, adotando a seguinte regra prática: \textit{nunca escrever o que não se diria};
*** termos coloquiais ou de gíria devem ser usados com \textit{extrema} parcimônia (ou mesmo nem serem utilizados) e apenas em casos muito especiais, para não darem ao leitor a idéia de vulgaridade e descaracterizar o trabalho;
*** ser rigoroso na escolha das palavras do texto, desconfiando dos sinônimos perfeitos ou de termos que sirvam para todas as ocasiões; em geral, há uma palavra para definir uma situação;
*** encadear o assunto de maneira suave e harmoniosa, evitando a criação de um texto onde os parágrafos se sucedem uns aos outros como compartimentos estanques, sem nenhuma fluência entre si;
*** ter um extremo cuidado durante a redação do texto, principalmente com relação às regras gramaticais e ortográficas da língua; geralmente todo o texto é escrito na forma impessoal do verbo, não se utilizando, portanto, de termos em primeira pessoa, seja do plural ou do singular.

* Conteúdo
** Como funciona um TTS
*** Front-end
**** Pré-processamento
**** G2P
*** Back-end
**** Sintetizador de fala
** Sistemas TTS existentes
*** MBROLA
**** LianeTTS
*** MaryTTS
*** Festival / FestVox
*** espeak
*** kaldi
*** Novos, baseados em DNN / Machine Learning
**** Lyrebird
**** Wavenet
**** Merlin (https://github.com/CSTR-Edinburgh/merlin)
** Tipos de prosódia
*** Suprasegmental
*** Afetiva
*** O terceiro lá
** Teorias e modelos de entoação
*** Discretos vs contínuos
**** Fujisaki
**** ToBI (Autosegmental-Metrical)
** Desafios de prosódia?
*** Extra-textual, natureza desambiguadora
*** Entoação declarativa neutra
** Modelo proposto pelo trabalho
*** Similar ao LianeTTS
*** Pré-processamento, G2P, etc pelo espeak-ng
*** Back-end é o MBROLA
* Bibliografia principal
** TTS book (Dutoit)
** Prosody book (Paul Taylor)
** Martin & Jurafsky
** Pitch analysis by synthesis! Melodic contours based on _intention_

* Apresentação
** Exemplos de prosódia
*** Halt and Catch Fire - It speaks (sistemas TTS)
*** Fleet Foxes - An Argument (prosódia "pura")
*** 2001 - Odisseia no Espaço vs "Her"
*** Prosódia e pontuação
**** https://medium.com/@neuroecology/punctuation-in-novels-8f316d542ec4
**** Memórias Póstumas de Brás Cubas - O velho diálogo de Adão e Eva http://memorias2em.blogspot.com.br/2008/11/capitulo-lv-o-velho-dilogo-de-ado-e-eva.html
** Simples: os sistemas texto fala hoje têm uma deficiência perceptível na parte de prosódia
** Além disso, não há maneira de especificar facilmente a prosódia a ser gerada
** Mesmas frases podem ser faladas de um jeito diferente
** "Frases iguais podem ser faladas de um jeito diferente?"
** "Frases iguais podem ser faladas de um jeito diferente!"

* Reunião Prolo
** João Antonio Moraes pra banca?
*** jamoraes2@br.inter.net
